### ISSUE TITLE
Getting error while trying to nest one router inside another one

### ISSUE THREAD

**Issue by devjayprakash** [ishtms/velocy#3]
bug that i'm getting 

```sh
node:_http_outgoing:879
    throw new ERR_INVALID_ARG_TYPE(
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
    at write_ (node:_http_outgoing:879:11)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at file:///Users/jayprakashpathak/projects/servertest/index.js:7:7
    at Router.handleRequest (/Users/jayprakashpathak/projects/servertest/node_modules/velocy/lib/velocy.js:122:19)
    at Server.<anonymous> (/Users/jayprakashpathak/projects/servertest/node_modules/velocy/lib/velocy.js:253:16)
    at Server.emit (node:events:514:28)
    at parserOnIncoming (node:_http_server:1143:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.10.0
```

**Comment by Zen-cronic** [comment]
Hey, I dug into it and the reason is that the `Request` and `Response` class were not used as the req and res in the `async handleRequest` method. This will make sure that the req object can access the URL parameters. 

```javascript

 async handleRequest(nativeReq, nativeRes) {
        // const req = new Request(nativeReq);
        // const res = new Response(nativeRes);

        const { method, url } = nativeReq;
        ...
```

Plus, the native end() method of a response object expects the optional first arg to be either of string, Buffer, or Uint8Array. Check [the docs](https://nodejs.org/api/http.html#responseenddata-encoding-callback). 

However after making the first change,` req.params` should be used instead of `req.extractedParams `in the authors's example. 
```javascript
function showUserInfo(req, res) {
  res.writeHead(200, { "Content-Type": "application/json" });

 // res.end("/users/:id: " + JSON.stringify({ user: req.extractedParams.id }));
   res.end("/users/:id: " + JSON.stringify({ user: req.params.id }));
}
```
